### ISSUE TITLE
mobile: undefined error when document reconnects

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#10234]
### Describe the Bug
Undefined JSerror when reconnecting in mobile view

### Steps to Reproduce
1. Open writer document with mobile view using 'Response Design View'
2. Stop the server using (Ctrl + C)
3. Start server again

### Expected Behavior
No JSError

### Actual Behavior
Undefined JSError

### Screenshots
![image](https://github.com/user-attachments/assets/59e9bd97-8743-4949-be3d-7ea4d2e8b630)

```
global.js:562 Exception TypeError: Cannot read properties of null (reading 'resetInCore') emitting event status: {"mode": 0,"pagerectangles": [ [284, 284, 12240, 15840] ],"viewid": 4,"height": 16408,"width": 12808,"selectedpart": 0,"partscount": 1,"type": "text"}
TypeError: Cannot read properties of null (reading 'resetInCore')
    at NewClass._onStatusMsg (http://localhost:9980/browser/018701cf/src/core/Socket.js:1378:49)
    at NewClass._onMessage (http://localhost:9980/browser/018701cf/src/core/Socket.js:1154:18)
    at NewClass._emitSlurpedEvents (http://localhost:9980/browser/018701cf/src/core/Socket.js:342:30)
    at http://localhost:9980/browser/018701cf/src/core/Socket.js:299:22
logWithCool	@	global.js:562
_emitSlurpedEvents	@	Socket.js:414
(anonymous)	@	Socket.js:358
setTimeout		
_queueSlurpEventEmission	@	Socket.js:354
_slurpMessage	@	Socket.js:483
```

**Comment by Darshan-upadhyay1110** [comment]
The crashing code no longer exists: the reported TypeError came from _onStatusMsg in browser/src/core/Socket.js reading 'resetInCore', and that whole path has since been rewritten (Socket.js became browser/src/app/Socket.ts with a new guarded _reconnecting branch; 'resetInCore' is gone from the codebase entirely). The specific error can no longer occur as reported; please file a fresh issue if reconnect on mobile still throws.

[d9eabce91330](https://github.com/CollaboraOnline/online/commit/d9eabce913305926cd513b06cf2aaa7b57128e8b)
browser: ts: rename SocketBase.ts => Socket.ts
