### ISSUE TITLE
Android : "LO Activity" shortcut crash

### ISSUE THREAD

**Issue by shuvashish76** [CollaboraOnline/online#4951]
**Describe the bug**
App crashed when clicked on LO Activity shortcut.
Shortcut created using [AppManager](https://github.com/MuntashirAkon/AppManager).
![Screenshot_2022-06-26-05-33-57](https://user-images.githubusercontent.com/48226312/175794149-16475822-e98d-4bbc-9c05-081a68f9fc4d.jpeg)
I was trying create a shortcut to launcher homescreen using AM. Though it is not caused by Collabora directly, it's a crash nevertheless.

**Crash Logs**

```
FATAL EXCEPTION: main
Process: com.collabora.libreoffice, PID: 23477
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.collabora.libreoffice/org.libreoffice.androidlib.LOActivity}: java.lang.NullPointerException: url
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: url
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
	at android.content.ContentResolver.getType(ContentResolver.java:557)
	at org.libreoffice.androidlib.LOActivity.getMimeType(LOActivity.java:1118)
	at org.libreoffice.androidlib.LOActivity.canDocumentBeExported(LOActivity.java:1154)
	at org.libreoffice.androidlib.LOActivity.initUI(LOActivity.java:342)
	at org.libreoffice.androidlib.LOActivity.init(LOActivity.java:252)
	at org.libreoffice.androidlib.LOActivity.onCreate(LOActivity.java:245)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	... 9 more

```
App version : **21.11.5.3 (89)**

**Comment by pedropintosilva** [comment]
Hi @shuvashish76 and thanks for taking the time to report this. Wouldn't be better to report this to the `AppManager` repository? Or do you get this crash also in other situations?

**Comment by jazevedo-coll** [comment]
This ticket has some age now and version 21.x is no longer developed. I will close this ticket. @shuvashish76 if you still have this issue with the latest version of Collabora Android app, then I ask that you make a new ticket.
