### ISSUE TITLE
calc: avoid large (bogus) invalidation in save

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7769]
Save a calc document with a draw-shape in it, such as the attached 
[SimpleSplit.ods](https://github.com/CollaboraOnline/online/files/13532213/SimpleSplit.ods)

hit-save; and notice the big 'ole invalidation:

Stack trace is:

```
Thread 1 "kitbroker_002" hit Breakpoint 2, SfxLokHelper::notifyInvalidation (pThisView=0x5a707b0, nInPart=0, pRect=0x7ffe315f4b80) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/lokhelper.cxx:635
635	    const int nPart = comphelper::LibreOfficeKit::isPartInInvalidation() ? nInPart : INT_MIN;
(gdb) bt
#0  SfxLokHelper::notifyInvalidation(SfxViewShell const*, int, tools::Rectangle const*) (pThisView=0x5a707b0, nInPart=0, pRect=0x7ffe315f4b80) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/lokhelper.cxx:635
#1  0x00007f5ce89bd147 in ScGridWindow::LogicInvalidatePart(tools::Rectangle const*, int) (this=0x58f8f60, pRectangle=<optimized out>, nPart=0) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/view/gridwin4.cxx:1759
#2  0x00007f5cf8fa1fda in vcl::Window::Invalidate(tools::Rectangle const&, InvalidateFlags) (this=0x58f8f60, rRect=..., nFlags=InvalidateFlags::NoErase) at /home/data/opt/libreoffice/co-23.05/vcl/source/window/paint.cxx:1164
#3  0x00007f5cfaad0b7a in SdrPaintView::InvalidateAllWin(tools::Rectangle const&) (this=0x5a8f190, rRect=...) at /home/data/opt/libreoffice/co-23.05/svx/source/svdraw/svdpntv.cxx:859
#4  0x00007f5cfaac87a3 in SdrPageView::InvalidateAllWin() (this=this@entry=0x5a8afa0) at /home/data/opt/libreoffice/co-23.05/svx/source/svdraw/svdpagv.cxx:201
#5  0x00007f5cfaad08af in SdrPageView::SetLayerVisible(rtl::OUString const&, bool) (bShow=false, rName="..."..., this=0x5a8afa0) at /home/data/opt/libreoffice/co-23.05/include/svx/svdpagv.hxx:188
#6  SdrPaintView::SetLayerVisible(rtl::OUString const&, bool) (this=0x5a8f190, rName="hidden", bShow=bShow@entry=false) at /home/data/opt/libreoffice/co-23.05/svx/source/svdraw/svdpntv.cxx:418
#7  0x00007f5ce8a3bccf in ScTabView::UpdateLayerLocks() (this=0x5a70940) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/view/tabview5.cxx:383
#8  0x00007f5ce8a3bebf in ScTabView::UpdateLayerLocks() (this=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/view/tabview5.cxx:356
#9  0x00007f5ce8a4c923 in ScTabViewShell::Notify(SfxBroadcaster&, SfxHint const&) (this=0x5a707b0, rBC=..., rHint=...) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/view/tabvwsh5.cxx:264
#10 0x00007f5cfb30df69 in SfxBroadcaster::Broadcast(SfxHint const&) (this=this@entry=0x5773a60, rHint=...) at /home/data/opt/libreoffice/co-23.05/svl/source/notify/SfxBroadcaster.cxx:40
#11 0x00007f5ce86653e5 in ScDocShell::DoSaveCompleted(SfxMedium*, bool) (this=0x5773a60, pNewStor=<optimized out>, bRegisterRecent=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/docshell/docsh.cxx:2748
#12 0x00007f5cfb71db36 in SfxObjectShell::DoSave_Impl(SfxItemSet const*) (this=this@entry=0x5773a60, pArgs=pArgs@entry=0x7ffe315f5120) at /home/data/opt/libreoffice/co-23.05/sfx2/source/doc/objstor.cxx:2642
#13 0x00007f5cfb71df4b in SfxObjectShell::Save_Impl(SfxItemSet const*) (this=0x5773a60, pSet=pSet@entry=0x7ffe315f5120) at /home/data/opt/libreoffice/co-23.05/sfx2/source/doc/objstor.cxx:2709
#14 0x00007f5cfb751f67 in SfxBaseModel::storeSelf(com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&) (this=0x3d3b570, aSeqArgs=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sfx2/source/doc/sfxbasemodel.cxx:1694
#15 0x00007f5cfb6e668d in SfxStoringHelper::GUIStoreModel(com::sun::star::uno::Reference<com::sun::star::frame::XModel> const&, std::basic_string_view<char16_t, std::char_traits<char16_t> >, com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue>&, bool, SignatureState, bool) (this=this@entry=0x5e74f90, xModel=uno::Reference to (ScModelObj *) 0x3d3b600, aSlotName=Python Exception <class 'gdb.error'>: value has been optimized out
, aArgsSequence=uno::Sequence of length 3 = {...}, bPreselectPassword=bPreselectPassword@entry=false, nDocumentSignatureState=SignatureState::NOSIGNATURES, bIsAsync=false) at /home/data/opt/libreoffice/co-23.05/sfx2/source/doc/guisaveas.cxx:1516
#16 0x00007f5cfb702ea3 in SfxObjectShell::ExecFile_Impl(SfxRequest&) (this=0x5773a60, rReq=...) at /home/data/opt/libreoffice/co-23.05/sfx2/source/doc/objserv.cxx:1058
#17 0x00007f5cfb58ad3b in SfxShell::ExecuteSlot(SfxRequest&, SfxInterface const*) (this=0x5773a60, rReq=..., pIF=0x5774280, pIF@entry=0x0) at /home/data/opt/libreoffice/co-23.05/sfx2/source/control/shell.cxx:457
#18 0x00007f5ce8a4ddea in ScTabViewShell::ExecuteSave(SfxRequest&) (this=0x5a707b0, rReq=...) at /home/data/opt/libreoffice/co-23.05/sc/source/ui/view/tabvwsha.cxx:827

```

@caolanm prolly not a huge perf. issue, but perhaps interesting; I imagine if it affects Calc it affects other components too (?)

**Comment by mmeeks** [comment]
```
636	    const int nMode = pThisView->getEditMode();
(gdb) 
635	    const int nPart = comphelper::LibreOfficeKit::isPartInInvalidation() ? nInPart : INT_MIN;
(gdb) 
636	    const int nMode = pThisView->getEditMode();
(gdb) 
637	    pThisView->libreOfficeKitViewInvalidateTilesCallback(pRect, nPart, nMode);
(gdb) p nPart
$1 = 0
(gdb) p nMode
$2 = 0
(gdb) p pRect
$3 = (const tools::Rectangle *) 0x7ffe315f4b80
(gdb) p *pRect
$4 = {static RECT_EMPTY = -32767, mnLeft = 0, mnTop = 0, mnRight = 20971520, mnBottom = 268435456}

```

**Comment by caolanm** [comment]
https://gerrit.libreoffice.org/c/core/+/162242 for simple opt for this apparent case
