### ISSUE TITLE
Writer: Crash when clicking Layout > Hyphenation

### ISSUE THREAD

**Issue by neilguertincollabora** [CollaboraOnline/online#7849]
### Describe the Bug

Clicking on Layout > Hyphenation caused coolforkit to crash.

Output from `make run` is below.

I had one document open in two windows and was typing and clicking buttons in both. Most recently, I had inserted a page break and a manual break from the Layout menu.

After the crash, it automatically restarted and I was able to cause the crash again by clicking the same button.

### Steps to Reproduce
make run
Open hello world document in writer
Layout > Manual Break
Layout > Hyphenation

### Expected Behavior
No crash

### Actual Behavior
Crash

### Screenshots
Output from make run:
```
warn:vcl:55870:14166:vcl/jsdialog/jsdialogbuilder.cxx:1333: No notifier in JSInstanceBuilder::CreateMessageDialog
coolforkit: /home/neilguertin/build/libreoffice/vcl/source/window/window.cxx:3193: void vcl::Window::SetLOKNotifier(const vcl::ILibreOfficeKitNotifier*, bool): Assertion `pNotifier' failed.
kit-55870-14166 2023-12-18 10:55:19.105834 -0500 [ kitbroker_002 ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x3e80000da3e
Recent activity:
	trimAfterInactivity
	trimAfterInactivity
	unoCommand(26f) : Save - 2023-12-18 15:53:43
	trimAfterInactivity
	unoCommand(3ba) : InsertPagebreak - 2023-12-18 15:54:48
	unoCommand(3ba) : InsertBreak - 2023-12-18 15:55:02
	getTextSelection
	unoCommand(3ba) : Hyphenate - 2023-12-18 15:55:19

Backtrace 55870 - kit startup of 23.05.6.3 85e36b3bb7:
/home/neilguertin/build/collabora-online/coolforkit(_ZN7SigUtil13dumpBacktraceEv+0x83)[0x557e335141a9]
/home/neilguertin/build/collabora-online/coolforkit(+0x22e0e6)[0x557e335140e6]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7f8650e3afd0]
/lib/x86_64-linux-gnu/libc.so.6(+0x8ad3c)[0x7f8650e89d3c]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x12)[0x7f8650e3af32]
```

Backtrace from gdb:
```
#9  0x00007fafafe45472 in __GI_abort () at ./stdlib/abort.c:79
#10 0x00007fafafe45395 in __assert_fail_base (fmt=0x7fafaffb9a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fafa73896ef "pNotifier", 
    file=file@entry=0x7fafa7388c80 "/home/neilguertin/build/libreoffice/vcl/source/window/window.cxx", line=line@entry=3193, function=function@entry=0x7fafa7389678 "void vcl::Window::SetLOKNotifier(const vcl::ILibreOfficeKitNotifier*, bool)")
    at ./assert/assert.c:92
#11 0x00007fafafe53e32 in __GI___assert_fail (assertion=0x7fafa73896ef "pNotifier", file=0x7fafa7388c80 "/home/neilguertin/build/libreoffice/vcl/source/window/window.cxx", line=3193, 
    function=0x7fafa7389678 "void vcl::Window::SetLOKNotifier(const vcl::ILibreOfficeKitNotifier*, bool)") at ./assert/assert.c:101
#12 0x00007fafa6394500 in vcl::Window::SetLOKNotifier (this=0x55b6429494d0, pNotifier=0x0, bParent=false) at /home/neilguertin/build/libreoffice/vcl/source/window/window.cxx:3193
#13 0x00007fafa6212c10 in Dialog::ImplStartExecute (this=0x55b6429494d0) at /home/neilguertin/build/libreoffice/vcl/source/window/dialog.cxx:940
#14 0x00007fafa6213dd3 in Dialog::Execute (this=0x55b6429494d0) at /home/neilguertin/build/libreoffice/vcl/source/window/dialog.cxx:1072
#15 0x00007fafa6a4bebb in SalInstanceDialog::run (this=0x55b64293b9f0) at /home/neilguertin/build/libreoffice/vcl/source/app/salvtables.cxx:1854
#16 0x00007fafa6d93e1f in JSMessageDialog::run (this=0x55b64293b9f0) at /home/neilguertin/build/libreoffice/vcl/jsdialog/jsdialogbuilder.cxx:1862
#17 0x00007fafae6e4747 in SvxSpellWrapper::SpellNext (this=0x7ffdf266ba50) at /home/neilguertin/build/libreoffice/editeng/source/misc/splwrap.cxx:355
#18 0x00007fafae6e50d8 in SvxSpellWrapper::FindSpellError (this=0x7ffdf266ba50) at /home/neilguertin/build/libreoffice/editeng/source/misc/splwrap.cxx:464
#19 0x00007fafae6e40a8 in SvxSpellWrapper::SpellDocument (this=0x7ffdf266ba50) at /home/neilguertin/build/libreoffice/editeng/source/misc/splwrap.cxx:268
#20 0x00007faf953e6487 in SwView::HyphenateDocument (this=0x55b6424d41e0) at /home/neilguertin/build/libreoffice/sw/source/uibase/uiview/viewling.cxx:463
#21 0x00007faf953e51a4 in SwView::ExecLingu (this=0x55b6424d41e0, rReq=...) at /home/neilguertin/build/libreoffice/sw/source/uibase/uiview/viewling.cxx:208
#22 0x00007faf953c529a in SfxStubSwViewExecLingu (pShell=0x55b6424d41e0, rReq=...) at /home/neilguertin/build/libreoffice/workdir/SdiTarget/sw/sdi/swslots.hxx:14814
#23 0x00007fafac4c6de4 in SfxDispatcher::Call_Impl (this=0x55b6424cb890, rShell=..., rSlot=..., rReq=..., bRecord=true) at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:254
#24 0x00007fafac4cb08c in SfxDispatcher::PostMsgHandler (this=0x55b6424cb890, pReq=std::unique_ptr<SfxRequest> = {...}) at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:992
#25 0x00007fafac4f88bf in std::__invoke_impl<void, void (SfxDispatcher::*&)(std::unique_ptr<SfxRequest, std::default_delete<SfxRequest> >), SfxDispatcher*&, std::unique_ptr<SfxRequest, std::default_delete<SfxRequest> > > (
    __f=@0x55b6424ca260: (void (SfxDispatcher::*)(SfxDispatcher * const, std::unique_ptr<SfxRequest, std::default_delete<SfxRequest> >)) 0x7fafac4caf02 <SfxDispatcher::PostMsgHandler(std::unique_ptr<SfxRequest, std::default_delete<SfxRequest> >)>, __t=@0x55b6424ca270: 0x55b6424cb890) at /usr/include/c++/12/bits/invoke.h:74
```

### Desktop
 - **Collabora version:** 23.05.6.3
 - **OS and version:** Debian 12 bookworm
 - **Browser and version:** Firefox 115.5.0esr and Chromium 120.0.6099.109

### Additional Context
I also encountered https://github.com/CollaboraOnline/online/issues/7851 at the same time, maybe related

**Comment by timur-g** [comment]
I do not see crash, but Hyphenation does not do anything for me. With 21.11 I would still see confirmation diaglog, but I would not see changes - or my test doc was not proper. With 22.05.20 and 23.05.6, click on Hyphenation does not bring action.

**Comment by Ezinnem** [comment]
I was unable to reproduce any crash in the latest version.

For reference, I tested with:

COOLWSD version: 25.04.9.4 (git hash: d53fc816ab)
LOKit version: Collabora Office 25.04.9.4 (git hash: 9f18735b17)
Served by: Ubuntu 24.04.4 LTS
Server ID: d4cd95fd
WOPI host: Nextcloud 31.0.8.1 – richdocuments 8.7.8

Could you please retest this issue using a recent version of Collabora Online and share your findings?

@neilguertincollabora, please feel free to comment if you are still able to reproduce this issue.
