### ISSUE TITLE
Crash on Help > About > JSDialogs: View Widgets

### ISSUE THREAD

**Issue by neilguertincollabora** [CollaboraOnline/online#7851]
### Describe the Bug
Crash when clicking Help > About > JSDialogs: View Widgets

### Steps to Reproduce
make run
Open example document
Help > About > JSDialogs: View Widgets

### Expected Behavior
No crash

### Actual Behavior
Crash

### Screenshots
Output from make run:
```
coolforkit: /home/neilguertin/build/libreoffice/vcl/source/window/builder.cxx:555: VclBuilder::VclBuilder(vcl::Window*, const rtl::OUString&, const rtl::OUString&, rtl::OString, com::sun::star::uno::Reference<com::sun::star::frame::XFrame>, bool, const NotebookBarAddonsItem*): Assertion `models.insert(elem.m_sValue).second && "a liststore or treestore is used in duplicate widgets"' failed.
kit-182256-181508 2023-12-18 12:11:43.311563 -0500 [ kitbroker_003 ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x3e80002c7f0
Recent activity:
	load view: 236 doc: file:///tmp/user/docs/YgZ6UIwWvtMcG00r/hello-world.odt
	unoCommand(236) : ToolbarMode?Mode:string=notebookbar_online.ui - 2023-12-18 17:11:38
	unoCommand(236) : ChangeTheme - 2023-12-18 17:11:38
	unoCommand(236) : SidebarShow - 2023-12-18 17:11:38
	unoCommand(236) : WidgetTestDialog - 2023-12-18 17:11:43

Backtrace 182256 - kit startup of 23.05.6.3 85e36b3bb7:
/home/neilguertin/build/collabora-online/coolforkit(_ZN7SigUtil13dumpBacktraceEv+0x83)[0x55cd58e081a9]
/home/neilguertin/build/collabora-online/coolforkit(+0x22e0e6)[0x55cd58e080e6]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0)[0x7ff3b385afd0]
/lib/x86_64-linux-gnu/libc.so.6(+0x8ad3c)[0x7ff3b38a9d3c]
```

Backtrace from gdb:
```
#9  0x00007ff3b3845472 in __GI_abort () at ./stdlib/abort.c:79
#10 0x00007ff3b3845395 in __assert_fail_base (fmt=0x7ff3b39b9a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ff3aacb8b68 "models.insert(elem.m_sValue).second && \"a liststore or treestore is used in duplicate widgets\"", 
    file=file@entry=0x7ff3aacb87e0 "/home/neilguertin/build/libreoffice/vcl/source/window/builder.cxx", line=line@entry=555, 
    function=function@entry=0x7ff3aacb8aa0 "VclBuilder::VclBuilder(vcl::Window*, const rtl::OUString&, const rtl::OUString&, rtl::OString, com::sun::star::uno::Reference<com::sun::star::frame::XFrame>, bool, const NotebookBarAddonsItem*)") at ./assert/assert.c:92
#11 0x00007ff3b3853e32 in __GI___assert_fail (
    assertion=0x7ff3aacb8b68 "models.insert(elem.m_sValue).second && \"a liststore or treestore is used in duplicate widgets\"", 
    file=0x7ff3aacb87e0 "/home/neilguertin/build/libreoffice/vcl/source/window/builder.cxx", line=555, 
    function=0x7ff3aacb8aa0 "VclBuilder::VclBuilder(vcl::Window*, const rtl::OUString&, const rtl::OUString&, rtl::OString, com::sun::star::uno::Reference<com::sun::star::frame::XFrame>, bool, const NotebookBarAddonsItem*)") at ./assert/assert.c:101
#12 0x00007ff3a9b67730 in VclBuilder::VclBuilder (this=0x55cd6ab4c230, pParent=0x55cd6a48c3e0, sUIDir=..., sUIFile=..., sID=..., 
    xFrame=empty uno::Reference, bLegacy=false, pNotebookBarAddonsItem=0x0)
    at /home/neilguertin/build/libreoffice/vcl/source/window/builder.cxx:555
#13 0x00007ff3aa470023 in SalInstanceBuilder::SalInstanceBuilder (this=0x55cd6ab4b6a0, pParent=0x55cd6a48c3e0, rUIRoot=..., rUIFile=..., 
    rFrame=empty uno::Reference) at /home/neilguertin/build/libreoffice/vcl/source/app/salvtables.cxx:6989
#14 0x00007ff3aa788b1c in JSInstanceBuilder::JSInstanceBuilder (this=0x55cd6ab4b6a0, pParent=0x55cd6a71d790, rUIRoot=..., rUIFile=..., 
    bPopup=false) at /home/neilguertin/build/libreoffice/vcl/jsdialog/jsdialogbuilder.cxx:523
#15 0x00007ff3aa7a147a in std::make_unique<JSInstanceBuilder, weld::Widget*&, rtl::OUString const&, rtl::OUString const&> ()
    at /usr/include/c++/12/bits/unique_ptr.h:1065
#16 0x00007ff3aa789bd3 in JSInstanceBuilder::CreateDialogBuilder (pParent=0x55cd6a71d790, rUIRoot=..., rUIFile=...)
    at /home/neilguertin/build/libreoffice/vcl/jsdialog/jsdialogbuilder.cxx:649
#17 0x00007ff3a9b64b1a in Application::CreateBuilder (pParent=0x55cd6a71d790, rUIFile=..., bMobile=false, nLOKWindowId=0)
    at /home/neilguertin/build/libreoffice/vcl/source/window/builder.cxx:195
#18 0x00007ff3aa52f236 in weld::GenericDialogController::GenericDialogController (this=0x55cd6ab3ed30, pParent=0x55cd6a71d790, rUIFile=..., 
    rDialogId=..., bMobile=false) at /home/neilguertin/build/libreoffice/vcl/source/app/weldutils.cxx:53
#19 0x00007ff396582955 in WidgetTestDialog::WidgetTestDialog (this=0x55cd6ab3ed30, pParent=0x55cd6a71d930)
    at /home/neilguertin/build/libreoffice/cui/source/dialogs/widgettestdlg.cxx:14
#20 0x00007ff3962d7238 in std::_Construct<WidgetTestDialog, weld::Window*&> (__p=0x55cd6ab3ed30) at /usr/include/c++/12/bits/stl_construct.h:119
#21 0x00007ff3962d462e in std::allocator_traits<std::allocator<void> >::construct<WidgetTestDialog, weld::Window*&> (__p=0x55cd6ab3ed30)
    at /usr/include/c++/12/bits/alloc_traits.h:635
#22 0x00007ff3962d0e41 in std::_Sp_counted_ptr_inplace<WidgetTestDialog, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplac---Type <--Type <--Type--Ty--Type -------Ty--------Type <RET> for more, q to quit, c to continue without paging--
e<weld::Window*&> (this=0x55cd6ab3ed20, __a=...) at /usr/include/c++/12/bits/shared_ptr_base.h:604
#23 0x00007ff3962cc4b9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<WidgetTestDialog, std::allocator<void>, weld::Window*&> (this=0x7ffe1b6efad8, __p=@0x7ffe1b6efad0: 0x0, 
    __a=...) at /usr/include/c++/12/bits/shared_ptr_base.h:971
#24 0x00007ff3962c7b84 in std::__shared_ptr<WidgetTestDialog, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, weld::Window*&> (this=0x7ffe1b6efad0, __tag=...)
    at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#25 0x00007ff3962c4139 in std::shared_ptr<WidgetTestDialog>::shared_ptr<std::allocator<void>, weld::Window*&> (this=0x7ffe1b6efad0, __tag=...) at /usr/include/c++/12/bits/shared_ptr.h:464
#26 0x00007ff3962bbd5d in std::make_shared<WidgetTestDialog, weld::Window*&> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#27 0x00007ff3962a98f9 in AbstractDialogFactory_Impl::CreateWidgetTestDialog (this=0x55cd5acdd910, pParent=0x55cd6a71d930)
    at /home/neilguertin/build/libreoffice/cui/source/factory/dlgfact.cxx:1532
#28 0x00007ff3afdb5dd4 in SfxApplication::MiscExec_Impl (this=0x55cd6148cd00, rReq=...) at /home/neilguertin/build/libreoffice/sfx2/source/appl/appserv.cxx:697
#29 0x00007ff3afd9993c in SfxStubSfxApplicationMiscExec_Impl (pShell=0x55cd6148cd00, rReq=...) at /home/neilguertin/build/libreoffice/workdir/SdiTarget/sfx2/sdi/sfxslots.hxx:1292

#30 0x00007ff3afec6de4 in SfxDispatcher::Call_Impl (this=0x55cd6a6c6bc0, rShell=..., rSlot=..., rReq=..., bRecord=true)
    at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:254

#31 0x00007ff3afeca1ee in SfxDispatcher::Execute_ (this=0x55cd6a6c6bc0, rShell=..., rSlot=..., rReq=..., eCallMode=SfxCallMode::RECORD)
    at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:753
```

### Desktop
 - **Collabora version:** 23.05.6.3
 - **OS and version:** Debian 12 bookworm
 - **Browser and version:** Firefox 115.5.0esr and Chromium 120.0.6099.109

### Additional Context
I also encountered #7849 at the same time, maybe related

**Comment by eszkadev** [comment]
this should help: https://gerrit.libreoffice.org/c/core/+/160952

**Comment by eszkadev** [comment]
should be fixed now
