### ISSUE TITLE
Assertion while pasting

### ISSUE THREAD

**Issue by neilguertincollabora** [CollaboraOnline/online#7986]
### Describe the Bug
I had been investigating https://github.com/CollaboraOnline/online/issues/7985. At some point I tried to move a large area with Ctrl+X Ctrl+V. On pasting, this assertion was hit. The cells were mostly empty, some contained simple formulas, some were pasted with various paste features.

### Steps to Reproduce
Could not reproduce

### Stack trace
```
#5  <signal handler called>
#6  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#7  0x00007fd7c62a9d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#8  0x00007fd7c625af32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#9  0x00007fd7c6245472 in __GI_abort () at ./stdlib/abort.c:79
#10 0x00007fd7c6245395 in __assert_fail_base (fmt=0x7fd7c63b9a90 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fd7bd58980f "pNotifier", 
    file=file@entry=0x7fd7bd588da0 "/home/neilguertin/build/libreoffice/vcl/source/window/window.cxx", line=line@entry=3193, function=function@entry=0x7fd7bd589798 "void vcl::Window::SetLOKNotifier(const vcl::ILibreOfficeKitNotifier*, bool)")
    at ./assert/assert.c:92
#11 0x00007fd7c6253e32 in __GI___assert_fail (assertion=0x7fd7bd58980f "pNotifier", file=0x7fd7bd588da0 "/home/neilguertin/build/libreoffice/vcl/source/window/window.cxx", line=3193, 
    function=0x7fd7bd589798 "void vcl::Window::SetLOKNotifier(const vcl::ILibreOfficeKitNotifier*, bool)") at ./assert/assert.c:101
#12 0x00007fd7bc594520 in vcl::Window::SetLOKNotifier (this=0x55fff0c00a00, pNotifier=0x0, bParent=false) at /home/neilguertin/build/libreoffice/vcl/source/window/window.cxx:3193
#13 0x00007fd7bc412c30 in Dialog::ImplStartExecute (this=0x55fff0c00a00) at /home/neilguertin/build/libreoffice/vcl/source/window/dialog.cxx:940
#14 0x00007fd7bc413df3 in Dialog::Execute (this=0x55fff0c00a00) at /home/neilguertin/build/libreoffice/vcl/source/window/dialog.cxx:1072
#15 0x00007fd7bcc4bf4b in SalInstanceDialog::run (this=0x55fff0d401a0) at /home/neilguertin/build/libreoffice/vcl/source/app/salvtables.cxx:1854
#16 0x00007fd7bcf93f3f in JSMessageDialog::run (this=0x55fff0d401a0) at /home/neilguertin/build/libreoffice/vcl/jsdialog/jsdialogbuilder.cxx:1862
#17 0x00007fd7a42e4f52 in ScViewFunc::PasteFromClip (this=0x55fff022e3a0, nFlags=InsertDeleteFlags::ALL, pClipDoc=0x55fff06f0e90, nFunction=ScPasteFunc::NONE, bSkipEmptyCells=false, bTranspose=false, bAsLink=false, eMoveMode=INS_NONE, 
    nUndoExtraFlags=InsertDeleteFlags::NONE, bAllowDialogs=true) at /home/neilguertin/build/libreoffice/sc/source/ui/view/viewfun3.cxx:1080
#18 0x00007fd7a40c0cf8 in ScClipUtil::PasteFromClipboard (rViewData=..., pTabViewShell=0x55fff022e140, bShowDialog=true) at /home/neilguertin/build/libreoffice/sc/source/ui/view/cliputil.cxx:106
#19 0x00007fd7a4093c9a in ScCellShell::ExecuteEdit (this=0x55fff0258ec0, rReq=...) at /home/neilguertin/build/libreoffice/sc/source/ui/view/cellsh1.cxx:1433
#20 0x00007fd7a40870fb in SfxStubScCellShellExecuteEdit (pShell=0x55fff0258ec0, rReq=...) at /home/neilguertin/build/libreoffice/workdir/SdiTarget/sc/sdi/scslots.hxx:7540
#21 0x00007fd7c26c6f84 in SfxDispatcher::Call_Impl (this=0x55fff0223c80, rShell=..., rSlot=..., rReq=..., bRecord=true) at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:254
#22 0x00007fd7c26ca38e in SfxDispatcher::Execute_ (this=0x55fff0223c80, rShell=..., rSlot=..., rReq=..., eCallMode=SfxCallMode::RECORD) at /home/neilguertin/build/libreoffice/sfx2/source/control/dispatch.cxx:753
#23 0x00007fd7c26b62bb in SfxBindings::Execute_Impl (this=0x55fff0228120, aReq=..., pSlot=0x7fd7a5b9f1f0 <aScCellShellSlots_Impl+432>, pShell=0x55fff0258ec0) at /home/neilguertin/build/libreoffice/sfx2/source/control/bindings.cxx:1060
#24 0x00007fd7c27827be in SfxDispatchController_Impl::dispatch (this=0x55fff04ca520, aURL=..., aArgs=empty uno::Sequence, rListener=empty uno::Reference) at /home/neilguertin/build/libreoffice/sfx2/source/control/unoctitm.cxx:702
#25 0x00007fd7c27806f0 in SfxOfficeDispatch::dispatch (this=0x55fff04ca470, aURL=..., aArgs=empty uno::Sequence) at /home/neilguertin/build/libreoffice/sfx2/source/control/unoctitm.cxx:264
```

### Desktop
COOLWSD version: 23.05.6.4 (git hash: fc6fe42a)
LOKit version: Collabora Office 23.05.6.4 (git hash: 1380a82)
Served by: Debian GNU/Linux 12 (bookworm)

**Comment by Ezinnem** [comment]
I was unable to reproduce the assertion during pasting, and it appears the issue may have been resolved in a more recent version.

Closing this ticket as the issue is no longer reproducible in the latest version tested.

Tested with:

COOLWSD version: 25.04.9.4 (git hash: d53fc816ab)
LOKit version: Collabora Office 25.04.9.4 (git hash: 9f18735b17)
Served by: Ubuntu 24.04.4 LTS
Server ID: d4cd95fd
WOPI host: Nextcloud 31.0.8.1 – richdocuments 8.7.8

If the issue reoccurs, please feel free to reopen this ticket and share updated steps or logs.
