### ISSUE TITLE
DOMException: Failed to execute 'send' on 'XMLHttpRequest' on Chrome only

### ISSUE THREAD

**Issue by kt-solutions** [CollaboraOnline/online#857]
Hello,

we have installed CODE via docker-compose, turning off internal ssl and using nginx proxy.

The Problem is that in a Cross-Domain environment eg. sub1.domain.com requests collabora from sub2.domain.com to view in an iFrame the requested document it fails with the DOMException but only in Chrome.

`VM7810 bundle.js:formatted:30731 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://sub2.domain.com/loleaflet/46545ce/l10n/uno-localizations.json'.
    at request_JSON (https://sub2.domain.com/loleaflet/46545ce/bundle.js:1:754236)
    at String_ctr.<computed> (https://sub2.domain.com/loleaflet/46545ce/bundle.js:1:754580)
    at https://sub2.domain.com/loleaflet/46545ce/bundle.js:1:757943
    at https://sub2.domain.com/loleaflet/46545ce/bundle.js:1:758502`

if the request is called in sub2.domain.com ONLY than there are no issues, there is only the issue in cross-domain.

However in Firefox this works just fine.

Is this fixable, I have seen following on stack-overflow:
https://stackoverflow.com/questions/38640140/domexception-failed-to-execute-send-on-xmlhttprequest-on-chrome-only

Thank you!

**Comment by mmeeks** [comment]
Errors in the logs are not unexpected I think. Async-ness is a red-herring; the CSP issue is interesting; I wonder if you can provide from the network logs the full HTTP reply headers for this request - I would expect

    cspOss << "Content-Security-Policy: default-src 'none'; "
        "frame-src 'self' " << WELCOME_URL << " " << FEEDBACK_URL << " " << buyProduct <<

from FileManager.cpp - might be missing whatever alias for this sub2.domain.com to be allowed in there if that is not 'self', to fetch the l10n from (?)

Is there a machine with access that we can reproduce this on ?

Thanks !

**Comment by pedropintosilva** [comment]
@kt-solutions ^

**Comment by thebearon** [comment]
@kt-solutions is there a chance something sets `Access-Control-Allow-Origin` response header (not Collabora Online, possibly reverse proxy), which could be the culprit?

**Comment by julio1501** [comment]
@thebearon : my soultion ist to set this header on my subdomain sub1.domain.com:

<FilesMatch "\.(js|json)$">
    <IfModule mod_headers.c>
        SetEnvIf Origin "http(s)?://(www\.)?(<sub2.domain.com>)$" AccessControlAllowOrigin=$0
        Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
        Header merge Vary Origin
    </IfModule>
		</FilesMatch>
