### ISSUE TITLE
integration_tests/multiuser/writer/invalidations_spec.js is failing

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#8768]
### Describe the Bug
integration_tests/multiuser/writer/invalidations_spec.js is failing on CI

### Steps to Reproduce
1. checkout online `master`
1. `cd cypress_test`
2. `make check-multi spec=writer/invalidations_spec.js`

### Expected Behavior
Test pass

### Actual Behavior
Test fail:
```
  1 failing

  1) Joining a document should not trigger an invalidation
       Join after document save and modify:
     CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element:

`<div class="leaflet-layer" style="position: absolute; width: 642px; height: 484px;"></div>`

is being covered by another element:

`<div class="jsdialog ui-button-box end" id="">...</div>`

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at ensureIsDescendent (http://localhost:9900/__cypress/runner/cypress_runner.js:111921:68)
      at ensureDescendents (http://localhost:9900/__cypress/runner/cypress_runner.js:111972:5)
      at ensureDescendentsAndScroll (http://localhost:9900/__cypress/runner/cypress_runner.js:111978:14)
      at ensureElIsNotCovered (http://localhost:9900/__cypress/runner/cypress_runner.js:112109:5)
      at runAllChecks (http://localhost:9900/__cypress/runner/cypress_runner.js:112308:52)
      at retryActionability (http://localhost:9900/__cypress/runner/cypress_runner.js:112345:16)
      at tryCatcher (http://localhost:9900/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:9900/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:9900/__cypress/runner/cypress_runner.js:144278:68)
      at <unknown> (http://localhost:9900/__cypress/runner/cypress_runner.js:144219:14)
      at tryCatcher (http://localhost:9900/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:9900/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:9900/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:9900/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:9900/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:9900/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:9900/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (integration_tests/multiuser/writer/invalidations_spec.js:76:38)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 minute, 17 seconds                                                             │
  │ Spec Ran:     invalidations_spec.js                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  invalidations_spec.js                    01:17        2        1        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     01:17        2        1        1        -        -  

```

**Comment by caolanm** [comment]
FWIW while this has been failing for a while with new ci, locally for me it passes.

**Comment by hfiguiere** [comment]
this fail locally on my system.

**Comment by caolanm** [comment]
This is what I get from:

make run-multi spec=writer/invalidations_spec.js

[interactive.webm](https://github.com/CollaboraOnline/online/assets/833656/9f92f0d5-69f0-4d30-9236-3544ca46c395)

**Comment by caolanm** [comment]
Does https://github.com/CollaboraOnline/online/pull/8772 make any difference for you?

**Comment by hfiguiere** [comment]
Yes with that patch it does pass !

**Comment by caolanm** [comment]
oh, very good. With the patch reverted locally, does:

make run-multi spec=writer/invalidations_spec.js

fail in any way that might visually show what is different from my case?

**Comment by hfiguiere** [comment]
I don't get anything visual with `make run-multi spec=writer/invalidations_spec.js`. Just output in the terminal. So maybe i'm missing something.

**Comment by caolanm** [comment]
a pity, would be nice to know what exactly is the difference, anyhow works now

**Comment by hfiguiere** [comment]
Getting a different failure I didn't get before, on the same test.

**Comment by hfiguiere** [comment]
```
 1 failing

  1) Joining a document should not trigger an invalidation
       "before each" hook for "Join document":
     AssertionError: Timed out retrying after 20000ms: Expected to find element: `#document-canvas`, but never found it. Queried from:

              > cy.get(#iframe2, [object Object]).its(0.contentDocument, [object Object])

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Joining a document should n...`
      at documentChecks (integration_tests/common/helper.js:281:16)
      at checkIfDocIsLoaded (integration_tests/common/helper.js:320:8)
      at loadTestDoc (integration_tests/common/helper.js:275:4)
      at Object.beforeAll (integration_tests/common/helper.js:447:11)
      at Context.eval (integration_tests/multiuser/writer/invalidations_spec.js:10:30)
```
