### ISSUE TITLE
Calc zoom - LatLng helper issue (?)

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#9009]
I try to click + or - in calc status bar to zoom in / out:

bundle.js:10734 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at Bounds.contains (bundle.js:10734:12)
    at NewClass.setDesktopCalcViewOnZoom (bundle.js:11039:58)
    at NewClass.setZoom (bundle.js:11069:43)
    at NewClass.zoomOut (bundle.js:11085:22)
    at actionsMap.zoomout (bundle.js:8943:22)
    at Dispatcher.dispatch (bundle.js:9065:8)
    at HTMLDivElement.<anonymous> (bundle.js:27135:80)
    at HTMLDivElement.dispatch (bundle.js:978:35)
    at elemData.handle (bundle.js:940:91)

Exception
: 
TypeError: Cannot read properties of undefined (reading 'x') at Bounds.contains
this: Bounds
bounds: <value unavailable>
max: undefined
min: undefined
obj: {x: 913, y: 42198}
point: <value unavailable>

            var cursorInBounds = app.file.textCursor.visible ? cssBounds.contains({
                x: app.file.textCursor.rectangle.cX1,
                y: app.file.textCursor.rectangle.cY1
            }) : false;

* Weirdly:

this.getPixelBounds() is cssBounds - which is valid:

Bounds {min: Point, max: Point}
max: Point {x: 1743, y: 357687}
min: Point {x: 607, y: 356617}
[[Prototype]]:  Object

* How does that object get corrupted ?

Bounds.prototype.contains = function(obj) {
                var min, max;
                var bounds;
                var point;
                if (Array.isArray(obj) || obj instanceof L.Point || obj instanceof cool.SimplePoint) {
                    point = toPoint(obj)
                } else {
                    bounds = Bounds.toBounds(obj)
                }
                if (bounds) {
                    min = bounds.min;
                    max = bounds.max
                } else {
                    min = max = point
                }
                return min.x >= this.min.x && max.x <= this.max.x && min.y >= this.min.y && max.y <= this.max.y
            }

Array.isArray(obj) || obj instanceof L.Point || obj instanceof cool.SimplePoint

false

![image](https://github.com/CollaboraOnline/online/assets/122848/5647ccef-12e6-4743-b4d5-87871beeae45)

**Comment by mmeeks** [comment]
@gokaysatir is this closed ? =)

**Comment by gokaysatir** [comment]
Yep, i forgot to close the issue.
